// @host = 127.0.0.1
@host = 192.168.1.103
// localhost: 3000 | localhost https: 3443 | docker: 8443 | 
@port = 8443
@uri = https://{{host}}:{{port}}/api
@contentType = application/json

@userLoginEmail = mail@koakh.com
@userLoginPassword = 12345678

### ping
// @name ping

GET {{uri}}/app/ping HTTP/1.1
Content-Type: {{contentType}}

### userLogin
// @name userLogin

POST {{uri}}/users/login HTTP/1.1
Content-Type: {{contentType}}

{
  "user": {
    "email": "{{userLoginEmail}}",
    "password": "{{userLoginPassword}}"
  }
}

// articles

### createArticle
// @name createArticle

POST {{uri}}/articles HTTP/1.1
Content-Type: {{contentType}}

{
  "title": "Article #1",
  "description": "Article #1 Description",
  "body": "Article #1 : ",
  "tagList": ["red", "green"]
}
